rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - ree
  - jruby
  # Uncomment when I'll be able to bundle install properly locally
  #- rbx
  #- rbx-2.0

notifications:
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "nB9dAoIbRzLMURnlVH+kdt9r72qgUgEFqQzjNe4sUhhmNEdLXurE+XT2PU75\ndToRgVH6eWbak5yyT+l/2eKkx7SZLNGltzpczSeSf3OlFAWi5VXfCZWz6xqa\nU17zya2vKrXCWqFqOPCm15cSOKTiQ+N+ZsDAUQBJB00wdC0SLYo="
